version: 2
workflows:
  version: 2
  build:
    jobs:
      - build_and_test_client
      - deploy:
          requires:
            - build_and_test_client
          filters:
            branches:
              only:
                - master


jobs:
  build_and_test_client:
    working_directory: ~/pilgrimBC/client
    docker:
      - image: circleci/node:10.15.1
        environment:
          TZ: Europe/London
    steps:
      - checkout:
          path: ~/pilgrimBC
      - run:
          name: Installations 
          command: npm ci
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Run Linting
          command: npm run lint
      - run:
          name: Build app
          command: npm run build
      - persist_to_workspace:
          root: ~/pilgrimBC
          paths:
            - client/build
            - .firebaserc
            - firebase.json

  deploy:
    working_directory: ~/pilgrimBC
    docker:
      - image: circleci/node:10.15.1
    steps:
      - attach_workspace:
          at: ~/pilgrimBC
      - run:
          name: Install firebase CLI
          command: npm install firebase-tools
      - run: 
          name: Deploy to firebase hosting
          command: | 
            npx firebase deploy --token "$FIREBASE_TOKEN"